### ISSUE TITLE
Nothing Launched

### ISSUE THREAD

**Issue by zQueal** [8LWXpg/PowerToysRun-SSH#3]
Installed via PTR.

Configured destinations show up, but hitting enter does nothing.

**Comment by 8LWXpg** [comment]
this plugin uses Windows Terminal, can you try to run this in command line? 

```cmd
wt ssh <hostname>
```

https://github.com/8LWXpg/PowerToysRun-SSH/blob/master/SSH%2FHelpers%2FTerminalHelper.cs#L20-L20

**Comment by zQueal** [comment]
I missed the note;

> note: This plugin uses Windows Terminal.
